import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          "appbar": "Z. A. P. Franchise",
          "home_bottom": "Home",
          "payment_bottom": "Payments",
          "business_bottom": "Business\nSettings",
          "cust_info_bottom": "Customer\nInfo",
          "overview": "Overview",
          "profile": "Profile",
          "service": "Services",
          "courses": "Courses",
          "s_faq": "Support and FAQ's",
          "contact": "Contact Us",
          "feedback": "Feedback",
          "about": "About Us",
          "logout": "Logout",
          "name_profile": "Rashmi Joshi",
          "service_sold": "Services\nSold",
          "pay_collect": "Payment\nCollected",
          "pay_sent": "Payment\nSent",
          "first_name": "Enter First Name",
          "last_name": "Enter Last Name",
          "mob_no": "Enter Mobile Number",
          "alt_mob_no": "Enter Alternate Mobile Number",
          "email": "Enter Email",
          "dob": "Date Of Birth",
          "gender": "Gender",
          "state": "State",
          "city": "City",
          "area": "Area",
          "pin": "Pincode",
          "change_pass": "Change Password",
          "save": "Save",
          "select": "Select",
          "male": "Male",
          "female": "Female",
          "education": "Education",
          "submit": "Submit",
          "contact_add":
              "178, Zappkode Solutions, Near Borikar Institute, Kukde Layout, Rameshwari Road, Nagpur.\nPincode-440013",
          "pay_received": "Received Payment",
          "search": "Search Earned Commission",
          "total_amount": "Total Amount",
          "name": "Name",
          "date": "Date",
          "desc": "Description",
          "transaction": "Transaction Id",
          "pay_mode": "Payment Mode",
          "search_cust": "Search Customer",
          "cust_info": "Customer Info",
          "from": "From",
          "to": "To",
          "wallet": "Wallet",
          "today_payment": "Today's Payment",
          "earn_web": "Web Development",
          "earn_dm": "Digital Marketing",
          "earn_sd": "Software Development",
          "earn_gd": "Graphics Designing",
        },
        //HINDI LANGUAGE
        'hi_IN': {
          "appbar": "जेड ए पी फ्रेंचाइजी",
          "home_bottom": "घर",
          "payment_bottom": "भुगतान",
          "business_bottom": "व्यवसाय\nसमायोजन",
          "cust_info_bottom": "ग्राहक\nजानकारी",
          "overview": "अवलोकन",
          "profile": "प्रोफ़ाइल",
          "service": "सेवाएं",
          "courses": "पाठ्यक्रम",
          "s_faq": "समर्थन और प्रश्न",
          "contact": "संपर्क करें",
          "feedback": "प्रतिपुष्टि",
          "about": "हमारे बारे में",
          "logout": "लॉग आउट",
          "name_profile": "रश्मि जोशी",
          "service_sold": "सेवाएं\nबेची गई",
          "pay_collect": "भुगतान\nएकत्रित",
          "pay_sent": "भुगतान\nभेजा गया",
          "com_ear": "कमीशन\nअर्जित",
          "first_name": "प्रथम नाम दर्ज करें",
          "last_name": "अंतिम नाम दर्ज करो",
          "mob_no": "मोबाइल नंबर दर्ज करें",
          "alt_mob_no": "वैकल्पिक मोबाइल नंबर दर्ज करें",
          "email": "ईमेल दर्ज करें",
          "dob": "जन्म की तारीख",
          "gender": "लिंग",
          "state": "राज्य",
          "city": "शहर",
          "area": "क्षेत्र",
          "pin": "पिन कोड",
          "change_pass": "पासवर्ड बदलें",
          "save": "बचाना",
          "select": "चुनना",
          "male": "पुरुष",
          "female": "मादा",
          "education": "शिक्षा",
          "submit": "प्रस्तुत करना",
          "contact_add":
              "178, जैपकोड सॉल्यूशंस, बोरिकर इंस्टीट्यूट के पास, कुकडे लेआउट, रामेश्वरी रोड, नागपुर।\nपिनकोड-440013",
          "pay_received": "प्राप्त भुगतान",
          "search": "अर्जित कमीशन खोजें",
          "total_amount": "कुल राशि",
          "name": "नाम",
          "date": "तारीख",
          "desc": "विवरण",
          "transaction": "लेन-देन आईडी",
          "pay_mode": "भुगतान का प्रकार",
          "search_cust": "ग्राहक खोजें",
          "cust_info": "ग्राहक जानकारी",
          "from": "से",
          "to": "प्रति",
          "wallet": "बटुआ",
          "today_payment": "आज का भुगतान",
          "earn_web": "वेब डेवलपमेंट",
          "earn_dm": "डिजिटल विपणन",
          "earn_sd": "सॉफ्टवेयर डेवलपमेंट",
          "earn_gd": "ग्राफिक्स डिजाइनिंग",
        },
        //Marathi LANGUAGE
        'mr_IN': {
          "appbar": "Z. A. P. फ्रँचायझी",
          "home_bottom": "मुख्यपृष्ठ",
          "payment_bottom": "देयके",
          "business_bottom": "व्यवसाय\nसेटिंग्ज",
          "cust_info_bottom": "ग्राहक\nमाहिती",
          "overview": "आढावा",
          "profile": "प्रोफ़ाइल",
          "service": "सेवा",
          "courses": "अभ्यासक्रम",
          "s_faq": "समर्थन आणि प्रश्न",
          "contact": "संपर्क साधा",
          "feedback": "अभिप्राय",
          "about": "आमच्याबद्दल",
          "logout": "बाहेर पडणे",
          "name_profile": "रश्मी जोशी",
          "service_sold": "सेवा\nविकल्या",
          "pay_collect": "पेमेंट\nसंकलित",
          "pay_sent": "पेमेंट\nपाठवले",
          "com_ear": "कमिशन\nमिळवले",
          "first_name": "प्रथम नाव प्रविष्ट करा",
          "last_name": "आडनाव प्रविष्ट करा",
          "mob_no": "मोबाईल नंबर टाका",
          "alt_mob_no": "पर्यायी मोबाईल नंबर टाका",
          "email": "ईमेल प्रविष्ट करा",
          "dob": "जन्मतारीख",
          "gender": "लिंग",
          "state": "राज्य",
          "city": "शहर",
          "area": "क्षेत्रफळ",
          "pin": "पिन कोड",
          "change_pass": "पासवर्ड बदला",
          "save": "जतन करा",
          "select": "निवडा",
          "male": "पुरुष",
          "female": "स्त्री",
          "education": "शिक्षण",
          "submit": "प्रस्तुत करणे",
          "contact_add":
              "178, झापकोड सोल्युशन्स, बोरीकर संस्थेजवळ, कुकडे लेआउट, रामेश्वरी रोड, नागपूर.\nपिनकोड-440013",
          "pay_received": "पेमेंट मिळाले",
          "search": "शोध अर्जित आयोग",
          "total_amount": "एकूण रक्कम",
          "name": "नाव",
          "date": "दिनांक",
          "desc": "वर्णन",
          "transaction": "व्यवहार आयडी",
          "pay_mode": "पेमेंट मोड",
          "search_cust": "ग्राहक शोधा",
          "cust_info": "ग्राहक माहिती",
          "from": "पासून",
          "to": "ला",
          "wallet": "पाकीट",
          "today_payment": "आजचे पेमेंट",
          "earn_web": "वेब डेवलपमेंट",
          "earn_dm": "डिजिटल विपणन",
          "earn_sd": "सॉफ्टवेयर डेवलपमेंट",
          "earn_gd": "ग्राफिक्स डिजाइनिंग",
        }
      };
}
