import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          "appbar": "Z. A. P. Franchise",
          "home_bottom": "Home",
          "payment_bottom": "Payments",
          "business_bottom": "Business\nSettings",
          "cust_info_bottom": "Customer\nInfo",
          "overview": "Overview",
          "profile": "Profile",
          "service": "Services",
          "courses": "Courses",
          "s_faq": "Support and FAQ's",
          "contact": "Contact Us",
          "feedback": "Feedback",
          "about": "About Us",
          "logout": "Logout",
          "name_profile": "Rashmi Joshi",
          "service_sold": "Services\nSold",
          "pay_collect": "Payment\nCollected",
          "pay_sent": "Payment\nSent",
          "first_name": "Enter First Name",
          "last_name": "Enter Last Name",
          "mob_no": "Enter Mobile Number",
          "alt_mob_no": "Enter Alternate Mobile Number",
          "email": "Enter Email",
          "dob": "Date Of Birth",
          "gender": "Gender",
          "state": "State",
          "city": "City",
          "area": "Area",
          "pin": "Pincode",
          "change_pass": "Change Password",
          "save": "Save",
          "select": "Select",
          "male": "Male",
          "female": "Female",
          "education": "Education",
          "submit": "Submit",
          "contact_add":
              "178, Zappkode Solutions, Near Borikar Institute, Kukde Layout, Rameshwari Road, Nagpur.\nPincode-440013",
          "pay_received": "Received Payment",
          "search": "Search Earned Commission",
          "total_amount": "Total Amount",
          "name": "Name",
          "date": "Date",
          "desc": "Description",
          "transaction": "Transaction Id",
          "pay_mode": "Payment Mode",
          "search_cust": "Search Customer",
          "cust_info": "Customer Info",
          "from": "From",
          "to": "To",
          "wallet": "Wallet",
          "today_payment": "Today's Payment",
          "earn_web": "Web Development",
          "earn_dm": "Digital Marketing",
          "earn_sd": "Software Development",
          "earn_gd": "Graphics Designing",
          "Digital Marketing":"'Digital Marketing'",
          "Website development": "Website development",
          "Application Development":"Application Development",
          "Software development":"Software development",
          "First Name":"First Name",
          "Last Name":"Last Name",
          "Mobile Number":"Mobile Number",
          "Email":"Email",
          "Area":"Area",
          "City":"City",
          "State":"State",
          "Pin":"Pincode",
          "Search Engine Oprimization":"Search Engine Oprimization",
          "Social Media Optimization":"Social Media Optimization",
          "Email Marketing":"Email Marketing",
          "Whatsaap Marketing":"Whatsaap Marketing",
          "Google":"Google",
          "Instagram":"Instagram",
          "Facebook":"Facebook",
          "Ecommerce websites":"Ecommerce websites",
          "Personal websites":"Personal websites",
          "Portfolio websites":"Portfolio websites",
          "Small business websites":"Small business websites",
          "Blog websites":"Blog websites",
          "Native Mobile Apps":"Native Mobile Apps",
          "Hybrid Mobile Apps":"Hybrid Mobile Apps",
          "Android/ios":"Android/ios",
          "Web Apps":"Web Apps",
          "Application software":"Application software",
          "System software":"System software",
          "Driver software":"Driver software",
          "Middleware":"Middleware",
          "Programming software":"Programming software",
          "Submit":"Submit",
          "General":"General",
          "Still Need Help?":"Still Need Help?",
          "FAQ's":"FAQ's",
          "What is ZAP":"What is ZAP",
          " E-Governance app ":"ZAP is E-Governance app where you can register yourself to make agent and earn some money",
          "What if I forget the password?":"What if I forget the password?",
          "Just click on Forgot Password":"Just click on Forgot Password. Enter the required details and you can easily create a new password",
          "Is it necessary to provide a mobile number and email?":"Is it necessary to provide a mobile number and email?",
          "Yes, it is":"Yes, it i9s necessary to provide a mobile number, email is optional.",
          "Submitted successfully":"Submitted successfully",
          "Comments":"Comments",
          "Bugs":"Bugs",
          "Suggestions":"Suggestions",
          "Select type of feedback":"Select type of feedback",
          "Business Settings":"Business Settings",
          "Billing Details":"Billing Details",
          "Company Name":"Company Name",
          "Phone Number":"Phone Number",
          "Address":"Address",
          "Company PAN Number":"Company PAN Number",
          "Business Basic Details":"Business Basic Details",
          "Business Name":"Business Name",
          "Business Category":"Business Category",
          "Business Email":"Business Email",
          "Alternate Mobile No.":"Alternate Mobile No.",
          "Website Url":"Website Url",
          "Alternate Email":"Alternate Email",
          "Address Details":"Address Details",
          "District":"District",
          "Owner Details (Contact Person)":"Owner Details (Contact Person)",
          "Aadhaar Number":"Aadhaar Number",
          "Bank Details":"Bank Details",
          "Bank Account No.": "Bank Account No.",
          "Bank IFSC Code":"Bank IFSC Code",
          "Bank Name":"Bank Name",
          "Bank Branch": "Bank Branch",
          "Name of Legal Entity on Bank Account":"Name of Legal Entity on Bank Account",
          "Address of Legal Entity on Bank Account": "Address of Legal Entity on Bank Account",
          "Business Documents":"Business Documents",
          "Required Payment Integration":"Required Payment Integration",
          "Cancelled Cheque":"Cancelled Cheque",
          "Upload Image":"Upload Image","GSTIN Certificate":"GSTIN Certificate",
          "CIN Certificate":"CIN Certificate",
          "Udyog Aadhaar\nCertificate":"Udyog Aadhaar\nCertificate",
          "Address Proof":"Address Proof",
          "Attested copy of Pan\nCard of Legal Entity":"Attested copy of Pan\nCard of Legal Entity",
          "Signature proof of\nAuthorized Signatory":"Signature proof of\nAuthorized Signatory",
          "Company Registration\nCertificate":"Company Registration\nCertificate",
          "PayU Schedule Upload":"PayU Schedule Upload",
          "Business Logo":"Business Logo",
          "Authorised Signature":"Authorised Signature",
          "Business Settings updated successfully":"Business Settings updated successfully",
          "Uploads":"Uploads",
          "Notifications":"Notifications",
          "Enquiry for Backend Developer.":"Enquiry for Backend Developer.",
          "Enquiry for S.E.O.":"Enquiry for S.E.O.",
          "Enquiry for Digital Marketing.":"Enquiry for Digital Marketing.",
          "username":"username",
          "password":"password",
          "Okay i remember":"Okay i remember",
          "Okay i removed":"Okay i removed",
          "Enter Username": "Enter Username",
          "Remember Me?":"Remember Me?",
          "Forgot Password?":"Forgot Password?",
          "Login":"Login",
          "Don't have an account ? ":"Don't have an account ? ",
          "SignUp": "SignUp",
          "Yes, Logout!":" Yes, Logout!",
          "Cancel": "Cancel",
          "Are you sure you want to log out.":"Are you sure you want to log out.",
          "No":"No",
          "Yes":"Yes",
          "yes selected":"yes selected",
          "no selected":"no selected",
        },
        //HINDI LANGUAGE
        'hi_IN': {
          "appbar": "जेड ए पी फ्रेंचाइजी",
          "home_bottom": "घर",
          "payment_bottom": "भुगतान",
          "business_bottom": "व्यवसाय\nसमायोजन",
          "cust_info_bottom": "ग्राहक\nजानकारी",
          "overview": "अवलोकन",
          "profile": "प्रोफ़ाइल",
          "service": "सेवाएं",
          "courses": "पाठ्यक्रम",
          "s_faq": "समर्थन और प्रश्न",
          "contact": "संपर्क करें",
          "feedback": "प्रतिपुष्टि",
          "about": "हमारे बारे में",
          "logout": "लॉग आउट",
          "name_profile": "रश्मि जोशी",
          "service_sold": "सेवाएं\nबेची गई",
          "pay_collect": "भुगतान\nएकत्रित",
          "pay_sent": "भुगतान\nभेजा गया",
          "com_ear": "कमीशन\nअर्जित",
          "first_name": "प्रथम नाम दर्ज करें",
          "last_name": "अंतिम नाम दर्ज करो",
          "mob_no": "मोबाइल नंबर दर्ज करें",
          "alt_mob_no": "वैकल्पिक मोबाइल नंबर दर्ज करें",
          "email": "ईमेल दर्ज करें",
          "dob": "जन्म की तारीख",
          "gender": "लिंग",
          "state": "राज्य",
          "city": "शहर",
          "area": "क्षेत्र",
          "pin": "पिन कोड",
          "change_pass": "पासवर्ड बदलें",
          "save": "बचाना",
          "select": "चुनना",
          "male": "पुरुष",
          "female": "मादा",
          "education": "शिक्षा",
          "submit": "प्रस्तुत करना",
          "contact_add":
              "178, जैपकोड सॉल्यूशंस, बोरिकर इंस्टीट्यूट के पास, कुकडे लेआउट, रामेश्वरी रोड, नागपुर।\nपिनकोड-440013",
          "pay_received": "प्राप्त भुगतान",
          "search": "अर्जित कमीशन खोजें",
          "total_amount": "कुल राशि",
          "name": "नाम",
          "date": "तारीख",
          "desc": "विवरण",
          "transaction": "लेन-देन आईडी",
          "pay_mode": "भुगतान का प्रकार",
          "search_cust": "ग्राहक खोजें",
          "cust_info": "ग्राहक जानकारी",
          "from": "से",
          "to": "प्रति",
          "wallet": "बटुआ",
          "today_payment": "आज का भुगतान",
          "earn_web": "वेब डेवलपमेंट",
          "earn_dm": "डिजिटल विपणन",
          "earn_sd": "सॉफ्टवेयर डेवलपमेंट",
          "earn_gd": "ग्राफिक्स डिजाइनिंग",
          "Digital Marketing":"डिजिटल विपणन",
          "Website development":"वेबसाइट निर्माणकार्य",
          "Application Development":"एप्लीकेशन का विकास",
          "Software development":"सॉफ्टवेअर विकास",
          "First Name":"पहला नाम",
          "Last Name":"उपनाम",
          "Mobile Number":"मोबाइल नंबर",
          "Email":"ईमेल",
          "Area":"क्षेत्र",
          "City":"शहर",
          "State":"राज्य",
          "Pin":"पिन",
          "Search Engine Oprimization":"सर्च इंजन ओप्रिमाइजेशन",
          "Social Media Optimization":"सोशल मीडिया ऑप्टिमाइज़ेशन",
          "Email Marketing":"ईमेल व्यापार",
          "Whatsaap Marketing":"व्हाट्सएप मार्केटिंग",
          "Google":"गूगल",
          "Instagram":"इंस्टाग्राम",
          "Facebook":"फेसबुक",
          "Ecommerce websites":"ईकॉमर्स वेबसाइट",
          "Personal websites":"व्यक्तिगत वेबसाइट",
          "Portfolio websites":"पोर्टफोलियो वेबसाइट",
          "Small business websites":"लघु व्यवसाय वेबसाइट",
          "Blog websites":"ब्लॉग वेबसाइट",
          "Native Mobile Apps":"नेटिव मोबाइल ऐप्स",
          "Hybrid Mobile Apps":"हाइब्रिड मोबाइल ऐप्स",
          "Android/ios":"एंड्रॉइड/आईओएस",
          "Web Apps":"वेब ऐप्स",
          "Application software":"अनुप्रयोग प्रक्रिया सामग्री",
          "System software":"सिस्टम सॉफ्ट्वेयर",
          "Driver software":"ड्राइवर सॉफ्टवेयर",
          "Middleware":"मध्यस्थ",
          "Programming software":"प्रोग्रामिंग सॉफ्टवेयर",
          "Submit":"प्रस्तुत",
          "General":"सामान्य",
          "Still Need Help?":"अभी भी सहायता चाहिए?",
          "FAQ's":"प्रश्न",
          "What is SAE":"ZAP क्या है",
          " E-Governance app ":" ZAP ई-गवर्नेंस ऐप है जहां आप एजेंट बनाने और कुछ पैसे कमाने के लिए खुद को पंजीकृत कर सकते हैं ",
          "What if I forget the password?":"क्या होगा अगर मैं पासवर्ड भूल जाऊं?",
          "Just click on Forgot Password":"बस पासवर्ड भूल गए पर क्लिक करें। आवश्यक विवरण दर्ज करें और आप आसानी से एक नया पासवर्ड बना सकते हैं",
          "Is it necessary to provide a mobile number and email?":"क्या मोबाइल नंबर और ईमेल देना जरूरी है?",
          "Yes, it is":"हां, मोबाइल नंबर देना जरूरी है, ईमेल वैकल्पिक है।",
          "Submitted successfully":"सफलतापूर्वक जमा",
          "Comments":"टिप्पणियाँ",
          "Bugs":"बग",
          "Suggestions":"सुझाव",
          "Select type of feedback":"फ़ीडबैक का प्रकार चुनें",
          "Business Settings":"व्यवसाय सेटिंग",
          "Billing Details":"बिलिंग विवरण",
          "Company Name":"कंपनी का नाम",
          "Phone Number":"फ़ोन नंबर",
          "Address":"पता",
          "Company PAN Number":"कंपनी पैन नंबर",
          "Business Basic Details":"व्यापार बुनियादी विवरण",
          "Business Name":"व्यवास्यक नाम",
          "Business Category":"व्यापार वर्ग",
          "Business Email":"बिजनेस ईमेल",
          "Alternate Mobile No.":"वैकल्पिक मोबाइल नंबर",
          "Website Url":"वेबसाइट Url",
          "Alternate Email":"वैकल्पिक ईमेल",
          "Address Details":"पते का विवरण",
          "District":"ज़िला",
          "Owner Details (Contact Person)":"मालिक का विवरण (संपर्क व्यक्ति)",
          "Aadhaar Number":"आधार संख्या",
          "Bank Details":"बैंक विवरण",
          "Bank Account No.": "बैंक खाता संख्या",
          "Bank IFSC Code":"बैंक IFSC कोड",
          "Bank Name":"बैंक का नाम",
          "Bank Branch": "बैंक शाखा",
          "Name of Legal Entity on Bank Account":"बैंक खाते पर कानूनी इकाई का नाम",
          "Address of Legal Entity on Bank Account": "बैंक खाते पर कानूनी इकाई का पता",
          "Business Documents":"व्यावसायिक दस्तावेज़",
          "Required Payment Integration":"आवश्यक भुगतान एकीकरण",
          "Cancelled Cheque":"रद्द चेक",
          "Upload Image":"तस्विर अपलोड",
          "GSTIN Certificate":"GSTIN  प्रमाणपत्र",
          "CIN Certificate":"CIN प्रमाणपत्र",
          "Udyog Aadhaar\nCertificate":"उद्योग आधार\nप्रमाणपत्र",
          "Address Proof":"निवास प्रमाण पत्र",
          "Attested copy of Pan\nCard of Legal Entity":"कानूनी इकाई के पैन\nकार्ड की सत्यापित प्रति",
          "Signature proof of\nAuthorized Signatory":"अधिकृत हस्ताक्षरकर्ता का हस्ताक्षर प्रमाण\n",
          "Company Registration\nCertificate":"कंपनी पंजीकरण\nप्रमाणपत्र",
          "PayU Schedule Upload":"PayU शेड्यूल अपलोड",
          "Business Logo":"व्यापार लोगो",
          "Authorised Signature":"अधिकृत हस्ताक्षर",
          "Business Settings updated successfully":"व्यवसाय सेटिंग सफलतापूर्वक अपडेट की गईं",
          "Uploads":"अपलोड",
          "Notifications":"सूचनाएं",
          "Enquiry for Backend Developer.":"बैकएंड डेवलपर के लिए पूछताछ।",
          "Enquiry for S.E.O.":"S.E.O. के लिए पूछताछ",
          "Enquiry for Digital Marketing.":"डिजिटल मार्केटिंग के लिए पूछताछ।",
          "username":"उपयोगकर्ता नाम",
          "password":"पासवर्ड",
          "Okay i remember":"ठीक है मुझे याद है",
          "Okay i removed":"ठीक है मैंने हटा दिया",
          "Enter Username": "उपयोगकर्ता नाम दर्ज करें",
          "Remember Me?":"मुझे याद रखें?",
          "Forgot Password?":"पासवर्ड भूल गए?",
          "Login":"लॉग इन ",
          "Don't have an account ? ":"खाता नहीं है? ",
          "SignUp": "साइन अप करें",
          "Yes, Logout!":" हाँ, लॉगआउट!",
          "Cancel": "रद्द करना",
          "Are you sure you want to log out.":"क्या आप लॉग आउट करना चाहते हैं।",
          "No":"नहीं",
          "Yes":"हाँ",
          "yes selected":"हाँ चयनित",
          "no selected":"कोई चयनित नहीं",
        },
        //Marathi LANGUAGE
        'mr_IN': {
          "appbar": "Z. A. P. फ्रँचायझी",
          "home_bottom": "मुख्यपृष्ठ",
          "payment_bottom": "देयके",
          "business_bottom": "व्यवसाय\nसेटिंग्ज",
          "cust_info_bottom": "ग्राहक\nमाहिती",
          "overview": "आढावा",
          "profile": "प्रोफ़ाइल",
          "service": "सेवा",
          "courses": "अभ्यासक्रम",
          "s_faq": "समर्थन आणि प्रश्न",
          "contact": "संपर्क साधा",
          "feedback": "अभिप्राय",
          "about": "आमच्याबद्दल",
          "logout": "बाहेर पडणे",
          "name_profile": "रश्मी जोशी",
          "service_sold": "सेवा\nविकल्या",
          "pay_collect": "पेमेंट\nसंकलित",
          "pay_sent": "पेमेंट\nपाठवले",
          "com_ear": "कमिशन\nमिळवले",
          "first_name": "प्रथम नाव प्रविष्ट करा",
          "last_name": "आडनाव प्रविष्ट करा",
          "mob_no": "मोबाईल नंबर टाका",
          "alt_mob_no": "पर्यायी मोबाईल नंबर टाका",
          "email": "ईमेल प्रविष्ट करा",
          "dob": "जन्मतारीख",
          "gender": "लिंग",
          "state": "राज्य",
          "city": "शहर",
          "area": "क्षेत्रफळ",
          "pin": "पिन कोड",
          "change_pass": "पासवर्ड बदला",
          "save": "जतन करा",
          "select": "निवडा",
          "male": "पुरुष",
          "female": "स्त्री",
          "education": "शिक्षण",
          "submit": "प्रस्तुत करणे",
          "contact_add":
              "178, झापकोड सोल्युशन्स, बोरीकर संस्थेजवळ, कुकडे लेआउट, रामेश्वरी रोड, नागपूर.\nपिनकोड-440013",
          "pay_received": "पेमेंट मिळाले",
          "search": "शोध अर्जित आयोग",
          "total_amount": "एकूण रक्कम",
          "name": "नाव",
          "date": "दिनांक",
          "desc": "वर्णन",
          "transaction": "व्यवहार आयडी",
          "pay_mode": "पेमेंट मोड",
          "search_cust": "ग्राहक शोधा",
          "cust_info": "ग्राहक माहिती",
          "from": "पासून",
          "to": "ला",
          "wallet": "पाकीट",
          "today_payment": "आजचे पेमेंट",
          "earn_web": "वेब डेवलपमेंट",
          "earn_dm": "डिजिटल विपणन",
          "earn_sd": "सॉफ्टवेयर डेवलपमेंट",
          "earn_gd": "ग्राफिक्स डिजाइनिंग",
          "Digital Marketing":"डिजिटल मार्केटिंग",
          "Website development":"वेबसाइट विकास",
          "Application Development":"अनुप्रयोग विकास",
          "Software development":"सॉफ्टवेअर विकास",
          "First Name":"पहिले नाव",
          "Last Name":"आडनाव",
          "Mobile Number":"मोबाईल नंबर",
          "Email":"ईमेल",
          "Area":"क्षेत्रफळ",
          "City":"शहर",
          "State":"राज्य",
          "Pin":"पिन",
          "Search Engine Oprimization":"शोध इंजिन ऑप्टिमायझेशन",
          "Social Media Optimization":"सोशल मीडिया ऑप्टिमायझेशन",
          "Email Marketing":"ईमेल विपणन",
          "Whatsaap Marketing":"व्हॉट्सअॅप मार्केटिंग",
          "Google":"गूगल",
          "Instagram":"इंस्टाग्राम",
          "Facebook":"फेसबुक",
          "Ecommerce websites":"ईकॉमर्स वेबसाइट्स",
          "Personal websites":"वैयक्तिक वेबसाइट्स",
          "Portfolio websites":"पोर्टफोलिओ वेबसाइट्स",
          "Small business websites":"लहान व्यवसाय वेबसाइट्स",
          "Blog websites":"ब्लॉग वेबसाइट्स",
          "Native Mobile Apps":"मूळ मोबाइल अॅप्स",
          "Hybrid Mobile Apps":"हायब्रिड मोबाइल अॅप्स",
          "Android/ios":"एंड्रॉइड/आईओएस",
          "Web Apps":"वेब अॅप्स",
          "Application software":"अनुप्रयोग सॉफ्टवेअर",
          "System software":"सिस्टम सॉफ्टवेअर",
          "Driver software":"ड्रायव्हर सॉफ्टवेअर",
          "Middleware":"मिडलवेअर",
          "Programming software":"प्रोग्रामिंग सॉफ्टवेअर",
          "Submit":"प्रस्तुत",
          "General":"सामान्य",
          "Still Need Help?":"तरीही मदत हवी आहे?",
          "FAQ's":"प्रश्न",
          "What is ZAP":"ZAP म्हणजे काय",
          " E-Governance app ":"ZAP हे ई-गव्हर्नन्स अॅप आहे जिथे तुम्ही एजंट बनवण्यासाठी आणि काही पैसे कमवण्यासाठी स्वतःची नोंदणी करू शकता",
          "What if I forget the password?":"मी पासवर्ड विसरलो तर?",
          "Just click on Forgot Password":"फक्त पासवर्ड विसरला त्यावर क्लिक करा. आवश्यक तपशील प्रविष्ट करा आणि तुम्ही सहजपणे नवीन पासवर्ड तयार करू शकता",
          "Is it necessary to provide a mobile number and email?":"मोबाईल नंबर आणि ईमेल देणे आवश्यक आहे का?",
          "Yes, it is":"होय, मोबाईल नंबर देणे आवश्यक आहे, ईमेल ऐच्छिक आहे.",
          "Submitted successfully":"यशस्वीरित्या सबमिट केले",
          "Comments":"टिप्पण्या",
          "Bugs":"बग",
          "Suggestions":"सूचना",
          "Select type of feedback":"फीडबॅकचा प्रकार निवडा",
          "Business Settings":"व्यवसाय सेटिंग्ज",
          "Billing Details":"बिलिंग तपशील",
          "Company Name":"कंपनीचे नाव",
          "Phone Number":"फोन नंबर",
          "Address":"पत्ता",
          "Company PAN Number":"कंपनी पॅन क्रमांक",
          "Business Basic Details":"व्यवसाय मूलभूत तपशील",
          "Business Name":"व्यवसायाचे नाव",
          "Business Category":"व्यवसाय श्रेणी",
          "Business Email":"व्यवसाय ईमेल",
          "Alternate Mobile No.":"पर्यायी मोबाईल नंबर",
          "Website Url":"संकेतस्थळ Url",
          "Alternate Email":"पर्यायी ईमेल",
          "Address Details":"पत्ता तपशील",
          "District":"जिल्हा",
          "Owner Details (Contact Person)":"मालकाचे तपशील (संपर्क व्यक्ती)",
          "Aadhaar Number":"आधार क्रमांक",
          "Bank Details":"बँक तपशील",
          "Bank Account No.": "बँक खाते क्रमांक",
          "Bank IFSC Code":"बँक IFSC कोड",
          "Bank Name":"बँकेचे नाव",
          "Bank Branch": "बँक शाखा",
          "Name of Legal Entity on Bank Account":"बँक खात्यावरील कायदेशीर घटकाचे नाव",
          "Address of Legal Entity on Bank Account": "बँक खात्यावरील कायदेशीर घटकाचा पत्ता",
          "Business Documents":"व्यवसाय दस्तऐवज",
          "Required Payment Integration":"आवश्यक पेमेंट एकत्रीकरण",
          "Cancelled Cheque":"चेक रद्द केला",
          "Upload Image":"प्रतिमा अपलोड करा",
          "GSTIN Certificate":"GSTIN प्रमाणपत्र",
          "CIN Certificate":"CIN प्रमाणपत्र",
          "Udyog Aadhaar\nCertificate":"उद्योग आधार\nप्रमाणपत्र",
          "Address Proof":"पत्ता पुरावा",
          "Attested copy of Pan\nCard of Legal Entity":"कायदेशीर घटकाच्या\nपॅन कार्डची साक्षांकित प्रत",
          "Signature proof of\nAuthorized Signatory":"अधिकृत स्वाक्षरी करणाऱ्याचा\nस्वाक्षरीचा पुरावा",
          "Company Registration\nCertificate":"कंपनी नोंदणी\nप्रमाणपत्र",
          "PayU Schedule Upload":"PayU शेड्यूल अपलोड करा",
          "Business Logo":"व्यवसाय लोगो",
          "Authorised Signature":"अधिकृत सही",
          "Business Settings updated successfully":"व्यवसाय सेटिंग्ज यशस्वीरीत्या अपडेट केल्या",
          "Uploads":"अपलोड",
          "Notifications":"अधिसूचना",
          "Enquiry for Backend Developer.":"बॅकएंड विकसकासाठी चौकशी.",
          "Enquiry for S.E.O.":"S.E.O साठी चौकशी",
          "Enquiry for Digital Marketing.":"डिजिटल मार्केटिंगसाठी चौकशी.",
          "username":"वापरकर्तानाव",
          "password":"पासवर्ड",
          "Okay i remember":"ठीक आहे मला आठवते",
          "Okay i removed":"ठीक आहे मी काढले",
          "Enter Username": "वापरकर्तानाव प्रविष्ट करा",
          "Remember Me?":"माझी आठवण ठेवा?",
          "Forgot Password?":"पासवर्ड विसरलात?",
          "Login":"लॉगिन ",
          "Don't have an account ? ":"खाते नाही? ",
          "SignUp": "साइनअप करा",
          "Yes, Logout!":" होय, लॉगआउट!",
          "Cancel": "रद्द करा",
          "Are you sure you want to log out.":"तुमची खात्री आहे की तुम्ही लॉग आउट करू इच्छिता.",
          "No":"नाही",
          "Yes":"होय",
          "yes selected":"होय निवडले",
          "no selected":"निवडलेले नाही",
        }
      };
}
